### ISSUE TITLE
Broken tray icon right click menu on Plasma 5.25.3

### ISSUE THREAD

**Issue by HanPrower** [Thulinma/kalu#1]
I see there was some chatter about this on the AUR, but it feel silent with no extra info.

As the chatter in the AUR stated the issue popped up recently where the right click menu will not show up. In fact trying to get the menu to show up sometimes will open up other right click menus instead and just generally cause weird issues in the tray.

Below is the `journalctl` output whilst right clicking the icon.

```
Jan 23 10:56:59 smokey plasmashell[771]: Got invalid activation app_id: ""
Jan 23 10:56:59 smokey plasmashell[771]: Could not find DBusMenu interface, falling back to calling ContextMenu()
```

I'll add that I use Wayland, so not sure if that's a root cause. It does track with when I moved over to it - when Plasma 5.24 was released.

**Comment by guigirl42** [comment]
> I use Wayland

Hello. I came here to raise an Issue, but then saw your one. For me, in Arch KDE Plasma 5.24.x and 5.25.x including current 5.25.3, `kalu-kde` _System Tray_ icon works perfectly for all documented operations... but **only** when logged-into Plasma **X11** sessions. It has _never_ worked properly for me in any Plasma **Wayland** sessions, in any Plasma version [right-click is ignored, left-click does generate the update pop-up, but then clicking its _Update System_ button is ignored]. 

As lately i prefer to use Wayland rather than X11, it's disappointing that in effect, i cannot use `kalu` anymore [or rather, not until/unless i revert to X11].
***

For the Dev/s: is there any way that `kalu-kde` can be used in Plasma Wayland sessions, with all the functionality it has in X11?
***

For @HanPrower: do you have an ArchLinux Forum account? I don't, hence, cannot post this enquiry in https://aur.archlinux.org/packages/kalu-kde.

**Comment by HanPrower** [comment]
So recently I noticed that the right click menu "works". The menu is created as a new window which you can interact with, which closes the window and opens whatever you selected.

Not sure if this was a Kalu fix, or a Qt fix, or a Plasma fix, but it's better than nothing, so I'll close this 🤷

**Comment by guigirl42** [comment]
> So recently I noticed that the right click menu "works". The menu is created as a new window which you can interact with, which closes the window and opens whatever you selected.
> 
> Not sure if this was a Kalu fix, or a Qt fix, or a Plasma fix, but it's better than nothing, so I'll close this shrug

No, it does NOT work, for me. As i said above, it has NEVER worked, in Plasma Wayland sessions. Atm i'm in P 5.26.5, & i have kept trying it in EVERY Plasma update since my last post. LMB-click on the SysTray icon generates the News, AUR & Repo update dialogs as normal, but they're useless as clicking their action button is ignored. RMB-click on the SysTray icon is completely ignored. All those functions fully work in X11, but i want to stay in Wayland.

**Comment by guigirl42** [comment]
Hello, i don't know if anyone ever sees this Issue anymore given it was made `Closed`, but fwiw, `kalu` is still barely usable in Plasma Wayland, which since my last post has changed, now being Plasma 6.0.2. It's the same problem; **right-clicks are ignored on the System Tray icon**.
